
name: Check Anlakshya API status
on:
  schedule:
    - cron:  '*/10 * * * *'    # At every 10th minute
  workflow_dispatch:
jobs:
  Run:
    name: Check Anlakshya API status
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
            # Initialize variable
            $URL = "https://api-anlakshya.onrender.com/status"
            $Status = Invoke-RestMethod -URI $URL
            echo "API STATUS : $Status"
        shell: pwsh
